name: Rpi3b-QEMU-Test

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - 
      name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - 
      name: DownLoad RaspberryPi OS
      run: wget https://downloads.raspberrypi.org/raspios_armhf/images/raspios_armhf-2022-09-26/2022-09-22-raspios-bullseye-armhf.img.xz
    - 
      name: Unzip Image
      run: tar -xvf 2022-09-22-raspios-bullseye-armhf.img.xz
    - 
      name: ls
      run : ls && ls /2022-09-22-raspios-bullseye-armhf
    #- 
    #  name: Create Rpi3b QEMU
    #  run: qemu-system-aarch64  -machine type=raspi3b  -m 1024  -dtb D:\Rasppi\Kernel\bcm2710-rpi-3-b.dtb -kernel D:\Rasppi\Kernel\kernel8.img -drive id=hd-root,format=raw,file=D:\Rasppi\Img\2020-05-27-raspios-buster-full-armhf.img -append "'rw earlycon=pl011,0x3f201000 console=ttyAMA0 loglevel=8 root=/dev/mmcblk0p2 fsck.repair=yes net.ifnames=0 rootwait memtest=1 dwc_otg.fiq_fsm_enable=0"  -serial stdio -netdev user,id=net0,hostfwd=tcp::5555-:22  -usb -device usb-kbd -device usb-tablet  -device usb-net,netdev=net0       